main: com.rayzr522.advancedlist.AdvancedList
name: AdvancedList
version: 1.0.0
description: An advanced, prettier, per-role /list for Bukkit.
author: Rayzr
depend: [Vault]
commands:
  list:
    description: Lists all players currently online
    usage: /list
    permission: AdvancedList.use
  advancedlist:
    description: Admin command for AdvancedList
    usage: /advancedlist [reload]
    permission: AdvancedList.admin